### ISSUE TITLE
Can't start this programm

### ISSUE THREAD

**Issue by KlicOgogo** [Drapegnik/social-graph#1]
As a result of trying to start:

andrejka@andrejka:~/social-graph-master$ npm i
andrejka@andrejka:~/social-graph-master$ node server.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at EventEmitter.listen (/home/andrejka/social-graph-master/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/andrejka/social-graph-master/server.js:32:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

**Comment by Drapegnik** [comment]
EADDRINUSE :::3000 - у цябе ўжо заняты 3000 порт

**Comment by Drapegnik** [comment]
@AndrejKlicunou `EADDRINUSE :::3000` - port 3000 already in use, you should shutdown application that use this port or change port on `server.js:32`
